# random-number-operator-all-in-one.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: randomnumbergenerators.operators.sohamdalvi1011.io
spec:
  group: operators.sohamdalvi1011.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      minimum: 1
                      default: 1
                    image:
                      type: string
                      default: "sohamdalvi1011/random-num:v2"
                    port:
                      type: integer
                      default: 3000
                    pvc:
                      type: object
                      properties:
                        size:
                          type: string
                          pattern: '^[1-9]\d*[MGTP]i$'
                          default: "1Gi"
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "100m"
                            memory:
                              type: string
                              default: "128Mi"
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "200m"
                            memory:
                              type: string
                              default: "256Mi"
                    logLevel:
                      type: string
                      enum: ["debug", "info", "warn", "error"]
                      default: "info"
                    service:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                          default: "ClusterIP"
                        port:
                          type: integer
                          default: 3000
                mongodb:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    replicaCount:
                      type: integer
                      minimum: 1
                      default: 1
                    image:
                      type: string
                      default: "mongo:latest"
                    port:
                      type: integer
                      default: 27017
                    pvc:
                      type: object
                      properties:
                        size:
                          type: string
                          pattern: '^[1-9]\d*[MGTP]i$'
                          default: "256Mi"
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "250m"
                            memory:
                              type: string
                              default: "300Mi"
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "500m"
                            memory:
                              type: string
                              default: "800Mi"
                    service:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["ClusterIP", "NodePort"]
                          default: "ClusterIP"
                        port:
                          type: integer
                          default: 27017
      subresources:
        status: {}     
  scope: Namespaced
  names:
    plural: randomnumbergenerators
    singular: randomnumbergenerator
    kind: RandomNumberGenerator
    shortNames: ["rng"]

---
apiVersion: v1
kind: Namespace
metadata:
  name: rng-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-number-operator
  namespace: rng-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: random-number-operator
rules:
- apiGroups: ["operators.sohamdalvi1011.io"]
  resources: ["randomnumbergenerators"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "namespaces"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-number-operator
subjects:
- kind: ServiceAccount
  name: random-number-operator
  namespace: rng-system
roleRef:
  kind: ClusterRole
  name: random-number-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-operator
  namespace: rng-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-number-operator
  template:
    metadata:
      labels:
        app: random-number-operator
    spec:
      serviceAccountName: random-number-operator
      containers:
      - name: operator
        image: sohamdalvi1011/myapp-operator:v4
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      securityContext:
        runAsNonRoot: false
        #runAsUser: 1001
