apiVersion: operators.sohamdalvi1011.io/v1
kind: RandomNumberGenerator
metadata:
  name: test-rng
  namespace: default
spec:
  app:
    replicaCount: 2
    pvc:
      size: 1Gi
    service:
      type: "ClusterIP"
  mongodb:
    enabled: true
    replicaCount: 1
    pvc:
      size: 3Gi
