apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-html
data:
  custom.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Custom HTML</title>
    </head>
    <body>
        <h1>Hello from Custom HTML page!</h1>
        <p>This page is served alongside the default index.html.</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: custom-html
          mountPath: "/usr/share/nginx/html/custom.html"
          subPath: custom.html
      volumes:
      - name: custom-html
        configMap:
          name: nginx-custom-html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
