apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.soham.dev
spec:
  group: soham.dev
  names:
    kind: MyApp
    plural: myapps
    singular: myapp
    shortNames:
      - myapp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appImage:
                  type: string
                mongoImage:
                  type: string
                appPVCSize:
                  type: string
                mongoPVCSize:
                  type: string
                appReplicas:
                  type: integer
                  minimum: 1
                  default: 1
                mongoReplicas:
                  type: integer
                  minimum: 1
                  default: 1
