apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/
    server: 192.168.1.80
    readOnly: false
